### ISSUE TITLE
Error while setting up platform netatmo camera

### ISSUE THREAD

**Issue by Dennydd** [home-assistant/hassos#105]
```
Error while setting up platform netatmo

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/binary_sensor/netatmo.py", line 73, in setup_platform
    if not data.get_camera_names():
  File "/usr/lib/python3.6/site-packages/homeassistant/components/netatmo.py", line 82, in get_camera_names
    self.update()
  File "/usr/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 318, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/netatmo.py", line 113, in update
    self.camera_data = pyatmo.CameraData(self.auth, size=100)
  File "/usr/lib/python3.6/site-packages/smart_home/Camera.py", line 50, in __init__
    for e in self.rawData['homes'][i]['events']:
KeyError: 'events'
```
netatmo camera is not detected in HassOS 1.5 I tried this solution: https://github.com/home-assistant/home-assistant/issues/15047 modifying the camera.py file in another installation with Home Assistant and it works perfectly even from other users who had this problem. Is it possible to integrate this Fix also for HassOS in the next Update?

**Comment by pvizeli** [comment]
That is a home-assistant problem and need to be fixed inside Home-Assistant repository. Provide there a PR with wanted changes and it will be inside next release. This modification work also for hass.io but maybe the people should fix it inside core repository and then it need no workaround in future
