### ISSUE TITLE
19-01-18 09:22:22 ERROR (MainThread) [aiohttp.server] Error handling request

### ISSUE THREAD

**Issue by snelweg** [home-assistant/hassos#327]
Brandnew installation of HASSIO. Following https://www.home-assistant.io/hassio/installation/

Addonstore is empty and aiohttp is throwing errors again. 

> OSError:
 [Errno 117] No error information: '/data/addons/core/letsencrypt/icon.png'
19-01-18 09:19:04 INFO (MainThread) [hassio.hassos] Syncing configuration from USB with HassOS.
19-01-18 09:19:04 INFO (MainThread) [hassio.host.services] Restart local service hassos-config.service
19-01-18 09:19:04 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.RestartUnit on /org/freedesktop/systemd1
19-01-18 09:19:20 INFO (SyncWorker_5) [hassio.docker] Run command 'python3 -m homeassistant -c /config --script check_config' on homeassistant/raspberrypi3-homeassistant
19-01-18 09:20:30 INFO (MainThread) [hassio.homeassistant] Home Assistant config is valid
19-01-18 09:20:30 INFO (SyncWorker_17) [hassio.docker.interface] Stop homeassistant/raspberrypi3-homeassistant Docker application
19-01-18 09:20:33 INFO (SyncWorker_17) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant Docker application
19-01-18 09:20:35 INFO (SyncWorker_0) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.85.1
19-01-18 09:21:16 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-01-18 09:22:22 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/security.py", line 137, in token_validation
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/utils.py", line 32, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hassio/api/addons.py", line 87, in list
    ATTR_ICON: addon.with_icon,
  File "/usr/local/lib/python3.7/site-packages/hassio/addons/addon.py", line 474, in with_icon
    return self.path_icon.exists()
  File "/usr/local/lib/python3.7/pathlib.py", line 1329, in exists
    self.stat()
  File "/usr/local/lib/python3.7/pathlib.py", line 1151, in stat
    return self._accessor.stat(self)
OSError: [Errno 117] No error information: '/data/addons/core/letsencrypt/icon.png'`

**Comment by pvizeli** [comment]
I think there is a problem with your device. Not enough power or broken SD card

**Comment by jvanderneutstulen** [comment]
He did, errno 117 indicates filesystem corruption.
