### ISSUE TITLE
Snapshot not restoring

### ISSUE THREAD

**Issue by ndarilek** [home-assistant/hassos#407]
Made a snapshot under 2.11, tried restoring under 3.1. Only my HA release, configuration, and a single addon restored. No extra repositories or addons were configured.

Pretty sure I reported something similar a while ago and it was declared fixed. How do we debug this? Of all the functionality to fail, restoring a snapshot isn't on the list of things that should go wrong.

**Comment by pvizeli** [comment]
`su logs` on console

**Comment by cogneato** [comment]
You do need to add third party repos to the addon store before restoring any such addons.

**Comment by ndarilek** [comment]
Why, aren't they part of the backup?


I'll get some logs later today or tomorrow, been swamped at work and 
hadn't counted on needing to rebuild my server.

**Comment by ndarilek** [comment]
Here are logs of a snapshot restore. I've confirmed that the repositories for third-party addons are listed in the snapshot.json. These should presumably be added before the Docker images are retrieved.

```
[32m19-05-20 22:16:47 INFO (MainThread) [__main__] Initialize Hass.io setup[0m
[32m19-05-20 22:16:48 INFO (MainThread) [__main__] Setup HassIO[0m
[32m19-05-20 22:16:48 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/armv7-hassio-supervisor with version 164[0m
[32m19-05-20 22:16:48 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.systemd1 on /org/freedesktop/systemd1[0m
[32m19-05-20 22:16:48 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1[0m
[32m19-05-20 22:16:48 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.hostname1 on /org/freedesktop/hostname1[0m
[32m19-05-20 22:16:49 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1[0m
[32m19-05-20 22:16:49 INFO (MainThread) [hassio.utils.gdbus] Introspect de.pengutronix.rauc on /[0m
[32m19-05-20 22:16:49 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: de.pengutronix.rauc - /[0m
[32m19-05-20 22:16:49 INFO (MainThread) [hassio.host.info] Update local host information[0m
[32m19-05-20 22:16:49 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1[0m
[32m19-05-20 22:16:49 INFO (MainThread) [hassio.host.services] Update service information[0m
[32m19-05-20 22:16:49 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1[0m
[32m19-05-20 22:16:49 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}[0m
[32m19-05-20 22:16:49 INFO (MainThread) [hassio.host.services] Reload local service hassos-apparmor.service[0m
[32m19-05-20 22:16:49 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1[0m
[32m19-05-20 22:16:49 INFO (SyncWorker_1) [hassio.docker.interface] Attach to homeassistant/raspberrypi3-homeassistant with version 0.92.2[0m
[32m19-05-20 22:16:49 INFO (MainThread) [hassio.hassos] Detect HassOS 3.1 on host system[0m
[32m19-05-20 22:16:49 INFO (SyncWorker_0) [hassio.docker.hassos_cli] Found HassOS CLI homeassistant/armv7-hassio-cli with version 9[0m
[33m19-05-20 22:16:50 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/local/mopidy/config.json: required key not provided @ data['arch']. Got None[0m
[32m19-05-20 22:16:55 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/core repository[0m
[32m19-05-20 22:16:55 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/a0d7b954 repository[0m
[33m19-05-20 22:16:55 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/local/mopidy/config.json: required key not provided @ data['arch']. Got None[0m
[32m19-05-20 22:16:55 INFO (MainThread) [hassio.store] Load add-ons from store: 59 all - 59 new - 0 remove[0m
[32m19-05-20 22:16:55 INFO (MainThread) [hassio.addons] Found 8 installed add-ons[0m
[32m19-05-20 22:16:56 INFO (SyncWorker_5) [hassio.docker.interface] Attach to bestlibre/armv7-syncthing with version 1.1.0[0m
[32m19-05-20 22:16:56 INFO (SyncWorker_1) [hassio.docker.interface] Attach to hassioaddons/appdaemon3-armv7 with version v3.0.1[0m
[32m19-05-20 22:16:56 INFO (SyncWorker_3) [hassio.docker.interface] Attach to homeassistant/armv7-addon-ssh with version 5.4[0m
[32m19-05-20 22:16:56 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json[0m
[32m19-05-20 22:16:56 INFO (MainThread) [hassio.snapshots] Found 1 snapshot files[0m
[32m19-05-20 22:16:56 INFO (MainThread) [hassio.discovery] Load 0 messages[0m
[32m19-05-20 22:16:56 INFO (MainThread) [hassio.ingress] Load 0 ingress session[0m
[32m19-05-20 22:16:56 INFO (MainThread) [__main__] Run Hass.io[0m
[32m19-05-20 22:16:56 INFO (MainThread) [hassio.misc.dns] Start DNS port forwarding for host add-ons[0m
[32m19-05-20 22:16:56 INFO (MainThread) [hassio.api] Start API on 172.30.32.2[0m
[32m19-05-20 22:16:56 INFO (MainThread) [hassio.addons] Phase 'initialize' start 0 add-ons[0m
[32m19-05-20 22:16:56 INFO (MainThread) [hassio.addons] Phase 'system' start 2 add-ons[0m
[32m19-05-20 22:16:57 INFO (MainThread) [hassio.host.alsa] Update ALSA device list[0m
[32m19-05-20 22:16:57 INFO (MainThread) [hassio.host.alsa] Detect input device 0,0[0m
[31m19-05-20 22:16:57 ERROR (SyncWorker_4) [hassio.docker] Can't create container from addon_02defeca_pulseaudio: 404 Client Error: Not Found ("No such image: nolan/hassio-pulseaudio-armhf:latest")[0m
[32m19-05-20 22:16:57 INFO (SyncWorker_13) [hassio.docker.interface] Clean addon_53caca22_syncthing application[0m
[32m19-05-20 22:17:05 INFO (SyncWorker_13) [hassio.docker.addon] Start Docker add-on bestlibre/armv7-syncthing with version 1.1.0[0m
[31m19-05-20 22:17:05 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Addon.start() done, defined at /usr/src/hassio/hassio/addons/addon.py:459> exception=AddonsError()>[0m
Traceback (most recent call last):
  File "/usr/src/hassio/hassio/addons/addon.py", line 479, in start
    raise AddonsError() from None
hassio.exceptions.AddonsError[0m
[32m19-05-20 22:17:10 INFO (MainThread) [hassio.addons] Phase 'services' start 3 add-ons[0m
[31m19-05-20 22:17:10 ERROR (SyncWorker_1) [hassio.docker] Can't create container from addon_core_duckdns: 404 Client Error: Not Found ("No such image: homeassistant/armhf-addon-duckdns:latest")[0m
[32m19-05-20 22:17:10 INFO (SyncWorker_2) [hassio.docker.interface] Clean addon_core_ssh application[0m
[31m19-05-20 22:17:10 ERROR (SyncWorker_14) [hassio.docker] Can't create container from addon_02defeca_mycroft: 404 Client Error: Not Found ("No such image: nolan/hassio-mycroft-armhf:latest")[0m
[32m19-05-20 22:17:17 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-ssh with version 5.4[0m
[31m19-05-20 22:17:17 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Addon.start() done, defined at /usr/src/hassio/hassio/addons/addon.py:459> exception=AddonsError()>[0m
Traceback (most recent call last):
  File "/usr/src/hassio/hassio/addons/addon.py", line 479, in start
    raise AddonsError() from None
hassio.exceptions.AddonsError[0m
[31m19-05-20 22:17:17 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Addon.start() done, defined at /usr/src/hassio/hassio/addons/addon.py:459> exception=AddonsError()>[0m
Traceback (most recent call last):
  File "/usr/src/hassio/hassio/addons/addon.py", line 479, in start
    raise AddonsError() from None
hassio.exceptions.AddonsError[0m
[32m19-05-20 22:17:23 INFO (SyncWorker_17) [hassio.docker.interface] Start homeassistant/raspberrypi3-homeassistant[0m
[32m19-05-20 22:18:33 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance[0m
[32m19-05-20 22:18:33 INFO (MainThread) [hassio.addons] Phase 'application' start 3 add-ons[0m
[31m19-05-20 22:18:34 ERROR (SyncWorker_14) [hassio.docker] Can't create container from addon_7bce6681_esphomeyaml: 404 Client Error: Not Found ("No such image: ottowinter/esphomeyaml-hassio-armhf:latest")[0m
[32m19-05-20 22:18:34 INFO (SyncWorker_2) [hassio.docker.interface] Clean addon_a0d7b954_appdaemon3 application[0m
[31m19-05-20 22:18:34 ERROR (SyncWorker_16) [hassio.docker] Can't create container from addon_2ea540ea_mopidy: 404 Client Error: Not Found ("No such image: nolan/hassio-mopidy-armhf:latest")[0m
[32m19-05-20 22:18:41 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on hassioaddons/appdaemon3-armv7 with version v3.0.1[0m
[31m19-05-20 22:18:41 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Addon.start() done, defined at /usr/src/hassio/hassio/addons/addon.py:459> exception=AddonsError()>[0m
Traceback (most recent call last):
  File "/usr/src/hassio/hassio/addons/addon.py", line 479, in start
    raise AddonsError() from None
hassio.exceptions.AddonsError[0m
[31m19-05-20 22:18:41 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Addon.start() done, defined at /usr/src/hassio/hassio/addons/addon.py:459> exception=AddonsError()>[0m
Traceback (most recent call last):
  File "/usr/src/hassio/hassio/addons/addon.py", line 479, in start
    raise AddonsError() from None
hassio.exceptions.AddonsError[0m
[32m19-05-20 22:18:46 INFO (MainThread) [hassio.tasks] All core tasks are scheduled[0m
[32m19-05-20 22:18:46 INFO (MainThread) [hassio.core] Hass.io is up and running[0m
[32m19-05-20 22:18:51 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_appdaemon3[0m
[32m19-05-20 22:19:29 INFO (MainThread) [hassio.snapshots] Partial-Restore dec1ed3f start[0m
[32m19-05-20 22:20:03 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh[0m
[32m19-05-20 22:21:17 INFO (SyncWorker_14) [hassio.docker.interface] Stop homeassistant application[0m
[32m19-05-20 22:21:18 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m19-05-20 22:21:18 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3[0m
[31m19-05-20 22:21:18 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].[0m
[32m19-05-20 22:21:23 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m19-05-20 22:21:23 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3[0m
[31m19-05-20 22:21:23 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].[0m
[32m19-05-20 22:21:25 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh[0m
```

Thanks.

**Comment by ndarilek** [comment]
As I restore this backup again and again, more addons seem to appear in 
my dashboard. But they can't be started, so I suspect their images 
aren't being pulled. It's odd that they'd appear if that is the case.


I'll check the images on my host tomorrow and see if they're in fact 
getting pulled.

**Comment by ndarilek** [comment]
Please don't close, as this is definitely still a thing, and this is the 
second time I've opened an identical issue. I can once again provide a 
backup on request--I did so the first time but never heard anything in 
response. Not sure what more I can do to help debug this, and it worries 
me that an issue as serious as snapshots not restoring isn't taken more 
seriously.

**Comment by ndarilek** [comment]
Still important IMO. Backups...


My offer of a failing backup still stands. Because of the nature of a 
backup, I'd rather not provide it to just anyone. I know I've offered 
one in the past but never heard back about it.

**Comment by ndarilek** [comment]
*boing*

**Comment by kajmaj** [comment]
3.5 does not read snapshots from 2.12 at all.
Is there any way around?

**Comment by ndarilek** [comment]
...
